[workspace]
name = "simulations"
version = "0.1.0"
description = "TrickFire Simulations"
channels = ["conda-forge", "robostack-jazzy"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "osx-64"]

[dependencies]
python = ">=3.11,<3.13"
ros-jazzy-desktop = "*"
ros-jazzy-ros-gz = "*"
ros-jazzy-gz-ros2-control = "*"
ros-jazzy-ros2-controllers = "*"
ros-jazzy-rmw-cyclonedds-cpp = "*"
colcon-common-extensions = "*"

[activation]
scripts = [".devcontainer/pixi.sh"]

[pypi-dependencies]
sim = { path = ".", editable = true }
sim_common = { path = "gazebo/sim_common", editable = true }
filelock = "*"
pypresence = "*"
requests = "*"
