controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 60 # Hz

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

forward_velocity_controller:
  ros__parameters:
    joints:
      - fl_wheel
      - ml_wheel
      - bl_wheel
      - fr_wheel
      - mr_wheel
      - br_wheel
    interface_name: velocity
