<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>gazebo_code</name>
  <version>0.0.0</version>
  <description>Gazebo code for the Trickfire robot simulation</description>
  <maintainer email="tfrbtcs@uw.edu">Trickfire Robotics</maintainer>
  <license>TODO</license>
  <author>Calin Prutean</author>
  <author>Matej Stastny</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>models_and_worlds</depend>

  <test_depend>ament_lint_auto</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
