services:
  sim:
    environment:
      - DISPLAY
      - QT_SCALE_FACTOR=1.6
      - QT_ENABLE_HIGHDPI_SCALING=1
      - GDK_SCALE=2
      - GDK_DPI_SCALE=0.8
    build:
      target: dev
      args:
        USER_UID: "${UID:-1000}"
    volumes:
      - ${XDG_RUNTIME_DIR:-/tmp}:/run/host-runtime:ro
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        bind:
          create_host_path: true
