import sys
import pathlib
from typing import Literal
from . import _macos, _linux
from ..output import die, warn


def _is_wsl() -> bool:
    try:
        return "microsoft" in pathlib.Path("/proc/version").read_text(encoding="utf-8").lower()
    except Exception:  # pylint: disable=broad-except
        return False


def get_platform() -> Literal["macos", "linux", "wsl", "windows"]:
    if sys.platform == "darwin":
        return "macos"
    if sys.platform == "win32":
        return "windows"
    return "wsl" if _is_wsl() else "linux"


def cmake_clean(platform: str | None = None) -> None:
    if platform is None:
        platform = get_platform()

    from ..paths import WORKSPACE_DIR

    build_dir = WORKSPACE_DIR / "build"
    install_dir = WORKSPACE_DIR / "install"

    if platform == "linux" or platform == "wsl":
        saw_foreign = False
        for scan_dir in [build_dir, install_dir]:
            if not scan_dir.exists():
                continue
            try:
                import subprocess

                result = subprocess.run(
                    ["grep", "-Rqs", "/Users/", str(scan_dir)],
                    capture_output=True,
                    check=False,
                )
                if result.returncode == 0:
                    saw_foreign = True
                    break
            except Exception:  # pylint: disable=broad-except
                pass

        if saw_foreign:
            warn("Detected macOS-native artifacts in Linux/WSL workspace.")
            print("[INFO] Removing build/ and install/ for a clean Linux rebuild...")
            import shutil

            if build_dir.exists():
                shutil.rmtree(build_dir)
            if install_dir.exists():
                shutil.rmtree(install_dir)

    elif platform == "macos":
        # On macOS: remove Linux/devcontainer artifacts
        saw_foreign = False
        for scan_dir in [build_dir, install_dir]:
            if not scan_dir.exists():
                continue
            try:
                import subprocess

                result = subprocess.run(
                    [
                        "grep",
                        "-Rqs",
                        "-E",
                        "/workspace|/workspaces/|/root/|/home/",
                        str(scan_dir),
                    ],
                    capture_output=True,
                    check=False,
                )
                if result.returncode == 0:
                    saw_foreign = True
                    break
            except Exception:  # pylint: disable=broad-except
                pass

        if saw_foreign:
            warn("Detected Linux/devcontainer artifacts in macOS workspace.")
            print("[INFO] Removing build/ and install/ for a clean macOS rebuild...")
            import shutil

            if build_dir.exists():
                shutil.rmtree(build_dir)
            if install_dir.exists():
                shutil.rmtree(install_dir)

    # Check for stale CMake caches based on CMakeCache.txt contents
    if not build_dir.exists():
        return

    import subprocess
    import shutil

    stale_dirs = set()

    try:
        find_result = subprocess.run(
            ["find", str(build_dir), "-name", "CMakeCache.txt", "-type", "f"],
            capture_output=True,
            text=True,
            check=False,
        )
        for cache_file in find_result.stdout.strip().split("\n"):
            if not cache_file:
                continue

            cache_path = pathlib.Path(cache_file)
            cache_dir = cache_path.parent

            try:
                cache_content = cache_path.read_text(encoding="utf-8")
            except Exception:  # pylint: disable=broad-except
                continue

            # Check for "For build in directory" and "It was generated by CMake" lines
            expected_dir = None
            generated_by = None

            for line in cache_content.split("\n"):
                if line.startswith("# For build in directory:"):
                    expected_dir = line.replace("# For build in directory:", "").strip()
                elif line.startswith("# It was generated by CMake:"):
                    generated_by = line.replace("# It was generated by CMake:", "").strip()

            if expected_dir and expected_dir != str(cache_dir):
                stale_dirs.add(cache_dir)
                continue

            if platform == "linux" or platform == "wsl":
                if generated_by and ("/Users/" in generated_by or "/macos/" in generated_by):
                    stale_dirs.add(cache_dir)
            elif platform == "macos":
                if generated_by and (
                    "/workspace" in generated_by
                    or "/root/" in generated_by
                    or "/home/" in generated_by
                ):
                    stale_dirs.add(cache_dir)
    except Exception:  # pylint: disable=broad-except
        pass

    for stale_dir in sorted(stale_dirs):
        rel_path = (
            stale_dir.relative_to(WORKSPACE_DIR)
            if stale_dir.is_relative_to(WORKSPACE_DIR)
            else stale_dir
        )
        print(f"[INFO] Removing stale build directory: {rel_path}")
        shutil.rmtree(stale_dir)


def build_and_launch(robot: str, build_only: bool = False, no_build: bool = False) -> None:
    platform = get_platform()

    if platform == "windows":
        die("Windows is not supported for native builds. Use 'sim docker' instead.")

    if platform == "macos":
        _macos.build_and_launch(robot, build_only, no_build)
    else:  # linux or wsl
        _linux.build_and_launch(robot, build_only, no_build)
