"""Commands for building and launching native executables for Gazebo robots"""

import pathlib
import shutil
import subprocess
import sys
from typing import Literal

from . import _macos, _linux
from ..output import die, warn


def _is_wsl() -> bool:
    try:
        return "microsoft" in pathlib.Path("/proc/version").read_text(encoding="utf-8").lower()
    except Exception:  # pylint: disable=broad-except
        return False


def get_platform() -> Literal["macos", "linux", "wsl", "windows"]:
    """Detect the current platform, distinguishing between native Linux and WSL"""
    if sys.platform == "darwin":
        return "macos"
    if sys.platform == "win32":
        return "windows"
    return "wsl" if _is_wsl() else "linux"


def cmake_clean(platform: str | None = None) -> None:
    """Remove CMake build artifacts that may have been generated on a different platform"""
    from ..paths import WORKSPACE_DIR

    if platform is None:
        platform = get_platform()

    build_dir = WORKSPACE_DIR / "build"
    install_dir = WORKSPACE_DIR / "install"

    if platform in ("linux", "wsl"):
        foreign_pattern, foreign_label = "/Users/", "macOS-native"
        grep_args: list[str] = []
    else:
        foreign_pattern, foreign_label = (
            r"/workspace|/workspaces/|/root/|/home/",
            "Linux/devcontainer",
        )
        grep_args = ["-E"]

    for scan_dir in (build_dir, install_dir):
        if not scan_dir.exists():
            continue
        result = subprocess.run(
            ["grep", "-Rqs", *grep_args, foreign_pattern, str(scan_dir)],
            capture_output=True,
            check=False,
        )
        if result.returncode == 0:
            warn(
                f"Detected {foreign_label} artifacts — removing build/ and install/ for a clean rebuild"
            )
            shutil.rmtree(build_dir, ignore_errors=True)
            shutil.rmtree(install_dir, ignore_errors=True)
            break

    if not build_dir.exists():
        return

    for cache_file in build_dir.rglob("CMakeCache.txt"):
        try:
            content = cache_file.read_text(encoding="utf-8")
        except OSError:
            continue

        lines = content.splitlines()
        expected_dir = next(
            (
                line.removeprefix("# For build in directory:").strip()
                for line in lines
                if line.startswith("# For build in directory:")
            ),
            None,
        )
        generated_by = next(
            (
                line.removeprefix("# It was generated by CMake:").strip()
                for line in lines
                if line.startswith("# It was generated by CMake:")
            ),
            None,
        )

        wrong_path = expected_dir and expected_dir != str(cache_file.parent)
        wrong_platform = (
            platform in ("linux", "wsl")
            and generated_by
            and ("/Users/" in generated_by or "/macos/" in generated_by)
        ) or (
            platform == "macos"
            and generated_by
            and any(p in generated_by for p in ("/workspace", "/root/", "/home/"))
        )
        # Check whether any cmake tool paths recorded in the cache no longer exist.
        _TOOL_KEYS = ("CMAKE_COMMAND:INTERNAL=", "CMAKE_C_COMPILER:FILEPATH=", "CMAKE_CXX_COMPILER:FILEPATH=")
        broken_tools = any(
            not pathlib.Path(line.split("=", 1)[1].strip()).exists()
            for line in lines
            if any(line.startswith(k) for k in _TOOL_KEYS) and line.split("=", 1)[1].strip()
        )

        if wrong_path or wrong_platform or broken_tools:
            rel = (
                cache_file.parent.relative_to(WORKSPACE_DIR)
                if cache_file.parent.is_relative_to(WORKSPACE_DIR)
                else cache_file.parent
            )
            warn(f"Removing stale build directory: {rel}")
            shutil.rmtree(cache_file.parent)


def build_and_launch(robot: str, build_only: bool = False, no_build: bool = False) -> None:
    """Build the native executable for the specified robot and launch it"""
    platform = get_platform()

    if platform == "windows":
        die("Windows is not supported for native builds. Use 'sim docker' instead.")

    if platform == "macos":
        _macos.build_and_launch(robot, build_only, no_build)
    else:
        _linux.build_and_launch(robot, build_only, no_build)
