#!/usr/bin/env bash
# Host-side GUI environment detection.
#
# Run by the BASE devcontainer's `initializeCommand` on the host, before the
# container is (re)created — on both `devcontainer up` and VS Code's "Reopen in
# Container". It detects the host OS and writes docker/.env.host, which the base
# compose loads via `env_file`. That injects the platform-appropriate DISPLAY
# (and VirtualGL settings) into the container, so GUI forwarding works out of the
# box without hand-picking a macos/windows compose variant.
#
# This file is generated and host-specific — it is gitignored, never committed.
set -eu

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
repo_dir="$(cd "$script_dir/.." && pwd)"
out="$repo_dir/docker/.env.host"

uname_s="$(uname -s 2>/dev/null || echo unknown)"

# Emit the file: a provenance header line describing the host, followed by env
# assignments (KEY=VALUE, one per line — docker compose env_file format).
emit() {
    {
        echo "# generated by .devcontainer/detect-host-gui-env.sh — do not edit or commit"
        echo "# host: $1"
        shift
        printf '%s\n' "$@"
    } >"$out"
}

case "$uname_s" in
Darwin)
    # macOS: Docker Desktop's Linux VM can't bind-mount the host's X11/Wayland
    # sockets, so forward over the X11 protocol's TCP transport to XQuartz via
    # host.docker.internal, and render through VirtualGL (XQuartz's indirect
    # GLX can't give OGRE2 a usable GL context). See docker-compose-macos.yml.
    emit "macOS (XQuartz over TCP + VirtualGL)" \
        "DISPLAY=host.docker.internal:0" \
        "VGL_DISPLAY=:88" \
        "VGL_COMPRESS=proxy"
    ;;
MINGW* | MSYS* | CYGWIN*)
    # Native Windows (Git Bash / MSYS): same TCP forwarding to a Windows X
    # server (VcXsrv/X410). WSL2/WSLg reports as Linux below and uses sockets.
    emit "Windows (VcXsrv/X410 over TCP + VirtualGL)" \
        "DISPLAY=host.docker.internal:0" \
        "VGL_DISPLAY=:88" \
        "VGL_COMPRESS=proxy"
    ;;
Linux)
    # Native Linux or WSL2/WSLg: docker-compose-dev.yml bind-mounts the host's
    # X11/Wayland sockets, so pass the host DISPLAY straight through (:0 default).
    emit "Linux/WSLg (direct socket passthrough)" \
        "DISPLAY=${DISPLAY:-:0}"
    ;;
*)
    emit "unknown ($uname_s) — falling back to local display :0" \
        "DISPLAY=${DISPLAY:-:0}"
    ;;
esac
