#!/usr/bin/env bash
# Host-side environment detection for the (single) devcontainer.
#
# Run by the devcontainer's `initializeCommand` on the host, before the container
# is (re)created — on both `devcontainer up` and VS Code's "Reopen in Container".
# It detects the host OS and GPU and generates two gitignored files the compose
# stack reads, so one devcontainer config works everywhere with no variant to pick:
#
#   docker/.env       interpolation source (auto-loaded by compose): ports from
#                     .env.defaults + optional .env.local overrides, plus
#                     SIM_GPU_RUNTIME which flips `runtime: nvidia` on/off.
#   docker/.env.host  container env (loaded via compose `env_file`): DISPLAY +
#                     VirtualGL for GUI forwarding, and the NVIDIA_* vars when a
#                     usable GPU is present. Conditional vars are simply omitted
#                     when not applicable (an absent line means unset, not empty —
#                     which matters for __EGL_VENDOR_LIBRARY_FILENAMES).
#
# Both generated files are host-specific and gitignored — never committed.
set -eu

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
docker_dir="$(cd "$script_dir/../docker" && pwd)"
env_out="$docker_dir/.env"
host_out="$docker_dir/.env.host"
defaults="$docker_dir/.env.defaults"
overrides="$docker_dir/.env.local"

uname_s="$(uname -s 2>/dev/null || echo unknown)"

# Enable the nvidia runtime only when it will actually work: a driver that
# answers (nvidia-smi) AND docker with the nvidia runtime registered. Anything
# short of that stays on the default runtime, so non-GPU hosts never break.
gpu_available() {
    [ "$uname_s" = "Linux" ] || return 1
    command -v nvidia-smi >/dev/null 2>&1 || return 1
    nvidia-smi -L >/dev/null 2>&1 || return 1
    docker info --format '{{json .Runtimes}}' 2>/dev/null | grep -q '"nvidia"' || return 1
}

gpu_runtime=""
if gpu_available; then
    gpu_runtime="nvidia"
fi

# --- docker/.env: compose interpolation source (ports + GPU runtime) ---
{
    cat "$defaults"
    if [ -f "$overrides" ]; then
        echo ""
        echo "# --- user overrides (docker/.env.local) ---"
        cat "$overrides"
    fi
    echo ""
    echo "# --- host-detected (generated, do not edit) ---"
    echo "SIM_GPU_RUNTIME=$gpu_runtime"
} >"$env_out"

# --- docker/.env.host: container env (DISPLAY / VirtualGL / NVIDIA) ---
{
    echo "# generated by .devcontainer/detect-host-env.sh — do not edit or commit"
    case "$uname_s" in
    Darwin)
        # macOS: Docker Desktop's Linux VM can't bind-mount the host's X11/
        # Wayland sockets, so forward over the X11 protocol's TCP transport to
        # XQuartz via host.docker.internal. XQuartz's indirect GLX can't give
        # OGRE2 (Gazebo/RViz) a usable GL context, so render through VirtualGL
        # against a container-local headless X server (VGL_DISPLAY) and ship
        # finished frames as plain X11 images (VGL_COMPRESS=proxy). `sim gazebo`
        # wraps launches in vglrun.
        echo "# host: macOS (XQuartz over TCP + VirtualGL)"
        echo "DISPLAY=host.docker.internal:0"
        echo "VGL_DISPLAY=:88"
        echo "VGL_COMPRESS=proxy"
        ;;
    MINGW* | MSYS* | CYGWIN*)
        # Native Windows (Git Bash / MSYS): same TCP forwarding to a Windows X
        # server (VcXsrv/X410), same VirtualGL path as macOS. WSL2/WSLg reports
        # as Linux below and uses sockets. Needs bash on PATH (Git for Windows).
        echo "# host: Windows (VcXsrv/X410 over TCP + VirtualGL)"
        echo "DISPLAY=host.docker.internal:0"
        echo "VGL_DISPLAY=:88"
        echo "VGL_COMPRESS=proxy"
        ;;
    Linux)
        # Native Linux or WSL2/WSLg: docker-compose-dev.yml bind-mounts the
        # host's X11/Wayland sockets, so pass the host DISPLAY through (:0).
        echo "# host: Linux/WSLg (direct socket passthrough)"
        echo "DISPLAY=${DISPLAY:-:0}"
        ;;
    *)
        echo "# host: unknown ($uname_s) — falling back to local display :0"
        echo "DISPLAY=${DISPLAY:-:0}"
        ;;
    esac
    if [ -n "$gpu_runtime" ]; then
        # A working nvidia stack was detected; hand the GPU to the container.
        # (Only written when present — __EGL_VENDOR_LIBRARY_FILENAMES must be
        # absent, not empty, on non-GPU hosts or it breaks software EGL.)
        echo "# nvidia GPU detected (runtime: nvidia)"
        echo "NVIDIA_VISIBLE_DEVICES=all"
        echo "NVIDIA_DRIVER_CAPABILITIES=graphics,display,compute,utility"
        echo "__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json"
    fi
} >"$host_out"

echo "[detect-host-env] host=$uname_s gpu=${gpu_runtime:-none} -> wrote docker/.env, docker/.env.host"
