#!/usr/bin/env bash
set -eu

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
docker_dir="$(cd "$script_dir/../docker" && pwd)"
env_out="$docker_dir/.env"
host_out="$docker_dir/.env.host"
defaults="$docker_dir/.env.defaults"
overrides="$docker_dir/.env.local"

uname_s="$(uname -s 2>/dev/null || echo unknown)"

gpu_available() {
    [ "$uname_s" = "Linux" ] || return 1
    command -v nvidia-smi >/dev/null 2>&1 || return 1
    nvidia-smi -L >/dev/null 2>&1 || return 1
    docker info --format '{{json .Runtimes}}' 2>/dev/null | grep -q '"nvidia"' || return 1
}

gpu_runtime=""
if gpu_available; then
    gpu_runtime="nvidia"
fi

{
    cat "$defaults"
    if [ -f "$overrides" ]; then
        echo ""
        echo "# --- user overrides (docker/.env.local) ---"
        cat "$overrides"
    fi
    echo ""
    echo "# --- host-detected (generated, do not edit) ---"
    echo "SIM_GPU_RUNTIME=$gpu_runtime"
} >"$env_out"

{
    echo "# generated by .devcontainer/detect-host-env.sh — do not edit or commit"
    case "$uname_s" in
    Darwin)
        echo "# host: macOS (XQuartz over TCP + VirtualGL)"
        echo "DISPLAY=host.docker.internal:0"
        echo "VGL_DISPLAY=:88"
        echo "VGL_COMPRESS=proxy"
        ;;
    MINGW* | MSYS* | CYGWIN*)
        echo "# host: Windows (VcXsrv/X410 over TCP + VirtualGL)"
        echo "DISPLAY=host.docker.internal:0"
        echo "VGL_DISPLAY=:88"
        echo "VGL_COMPRESS=proxy"
        ;;
    Linux)
        echo "# host: Linux/WSLg (direct socket passthrough)"
        echo "DISPLAY=${DISPLAY:-:0}"
        ;;
    *)
        echo "# host: unknown ($uname_s) — falling back to local display :0"
        echo "DISPLAY=${DISPLAY:-:0}"
        ;;
    esac
    if [ -n "$gpu_runtime" ]; then
        echo "# nvidia GPU detected (runtime: nvidia)"
        echo "NVIDIA_VISIBLE_DEVICES=all"
        echo "NVIDIA_DRIVER_CAPABILITIES=graphics,display,compute,utility"
        echo "__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json"
    fi
} >"$host_out"

echo "[detect-host-env] host=$uname_s gpu=${gpu_runtime:-none} -> wrote docker/.env, docker/.env.host"
