<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
    <name>__ROBOT___bringup</name>
    <version>0.0.0</version>
    <description>Launch files for the __ROBOT__ simulation</description>
    <maintainer email="tfrbtcs@uw.edu">Trickfire Robotics</maintainer>
    <license>TODO</license>

    <depend>__ROBOT___description</depend>
    <depend>sim_common</depend>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <test_depend>ament_lint_auto</test_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>
