#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# cmake_clean.sh
# Deletes CMake artifacts built on the wrong platform.
# Usage: cmake_clean.sh [--mac|--linux]
#   --mac    running on macOS - remove Linux/devcontainer artifacts
#   --linux  running on Linux - remove macOS-native artifacts
# Defaults to auto-detecting the current OS when no flag is given.
# ------------------------------------------------------------------------------

TARGET_PLATFORM=""
for arg in "$@"; do
	case "$arg" in
	--mac) TARGET_PLATFORM="Darwin" ;;
	--linux) TARGET_PLATFORM="Linux" ;;
	esac
done
[ -n "$TARGET_PLATFORM" ] || TARGET_PLATFORM="$(uname)"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="${WORKSPACE_DIR:-"$(cd "$SCRIPT_DIR/.." && pwd)/robot-sim"}"

sanitize_cross_platform_artifacts() {
	local build_dir="$WORKSPACE_DIR/build"
	local install_dir="$WORKSPACE_DIR/install"

	if [ "$TARGET_PLATFORM" = "Linux" ]; then
		local saw_foreign=false
		for scan_dir in "$build_dir" "$install_dir"; do
			[ -d "$scan_dir" ] || continue
			if grep -Rqs "/Users/" "$scan_dir" 2>/dev/null; then
				saw_foreign=true
				break
			fi
		done
		if [ "$saw_foreign" = true ]; then
			echo "[WARN] Detected macOS-native artifacts in Linux/devcontainer workspace."
			echo "[INFO] Removing build/ and install/ for a clean Linux rebuild..."
			rm -rf "$build_dir" "$install_dir"
		fi
	elif [ "$TARGET_PLATFORM" = "Darwin" ]; then
		local saw_foreign=false
		for scan_dir in "$build_dir" "$install_dir"; do
			[ -d "$scan_dir" ] || continue
			if grep -Rqs "/workspace\|/workspaces/\|/root/\|/home/" "$scan_dir" 2>/dev/null; then
				saw_foreign=true
				break
			fi
		done
		if [ "$saw_foreign" = true ]; then
			echo "[WARN] Detected Linux/devcontainer artifacts in macOS workspace."
			echo "[INFO] Removing build/ and install/ for a clean macOS rebuild..."
			rm -rf "$build_dir" "$install_dir"
		fi
	fi

	[ -d "$build_dir" ] || return 0
	local -a stale_dirs=()
	while IFS= read -r cache_file; do
		local cache_dir expected_dir generated_by
		cache_dir="$(dirname "$cache_file")"
		expected_dir="$(sed -n 's|^# For build in directory: ||p' "$cache_file" | head -n 1)"
		generated_by="$(sed -n 's|^# It was generated by CMake: ||p' "$cache_file" | head -n 1)"
		if [ -n "$expected_dir" ] && [ "$expected_dir" != "$cache_dir" ]; then
			stale_dirs+=("$cache_dir")
			continue
		fi
		if [ "$TARGET_PLATFORM" = "Linux" ]; then
			if [[ "$generated_by" == *"/Users/"* ]] || [[ "$generated_by" == *"/macos/"* ]]; then
				stale_dirs+=("$cache_dir")
			fi
		elif [ "$TARGET_PLATFORM" = "Darwin" ]; then
			if [[ "$generated_by" == *"/workspace"* ]] || [[ "$generated_by" == *"/root/"* ]] || [[ "$generated_by" == *"/home/"* ]]; then
				stale_dirs+=("$cache_dir")
			fi
		fi
	done < <(find "$build_dir" -name "CMakeCache.txt" -type f 2>/dev/null || true)

	[ "${#stale_dirs[@]}" -gt 0 ] || return 0

	echo "[WARN] Detected stale CMake cache from a different environment."
	printf '%s\n' "${stale_dirs[@]}" | sort -u | while IFS= read -r stale_dir; do
		echo "[INFO] Removing stale build directory: ${stale_dir#"$WORKSPACE_DIR/"}"
		rm -rf "$stale_dir"
	done
}

sanitize_cross_platform_artifacts && echo "Cleaned CMake artifacts"
