#!/bin/bash
set -e

# --------------------------------------------------------------------------------------------
# Universal ROS2 Gazebo build + launch script
# Usage: ./launch_sim.sh <robot_name> [--build-only] [--no-build]
#
# Expects packages named:
#   <robot_name>_description  ->  URDF, meshes
#   <robot_name>_bringup      ->  launch files, configs
#   sim_worlds                ->  shared world files and models (Gazebo only)
#
# Example: ./launch_sim.sh arm
# --------------------------------------------------------------------------------------------

# Parse arguments
ROBOT_NAME=""
BUILD=true
LAUNCH=true

while [[ $# -gt 0 ]]; do
	case "$1" in
	--build-only)
		LAUNCH=false
		shift
		;;
	--no-build)
		BUILD=false
		shift
		;;
	--help)
		echo "Usage: $0 <robot_name> [--build-only] [--no-build]"
		exit 0
		;;
	-*)
		echo "[Error] Unknown option: $1"
		exit 1
		;;
	*)
		ROBOT_NAME="$1"
		shift
		;;
	esac
done

if [ -z "$ROBOT_NAME" ]; then
	echo "Usage: $0 <robot_name> [--build-only] [--no-build]"
	exit 1
fi

# Setup paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
WORKSPACE_DIR="$PROJECT_DIR/robot-sim"
SIM_COMMON_DIR="$PROJECT_DIR/robot-sim/sim_common/sim_common/"
LOG_DIR="$WORKSPACE_DIR/log"
LOG_PATH="$LOG_DIR/${ROBOT_NAME}-gazebo-$(date +'%Y-%m-%d_%H-%M').log"
cd "$WORKSPACE_DIR"

sanitize_cross_platform_artifacts() {
	[ "$(uname)" = "Linux" ] || return 0
	local saw_macos_paths=false
	for scan_dir in "$WORKSPACE_DIR/build" "$WORKSPACE_DIR/install"; do
		[ -d "$scan_dir" ] || continue
		if grep -Rqs "/Users/" "$scan_dir" 2>/dev/null; then
			saw_macos_paths=true
			break
		fi
	done
	if [ "$saw_macos_paths" = true ]; then
		echo "[WARN] Detected macOS-native artifacts in Linux/devcontainer workspace."
		echo "[INFO] Removing build/ and install/ for a clean Linux rebuild..."
		rm -rf "$WORKSPACE_DIR/build" "$WORKSPACE_DIR/install"
	fi

	local build_dir="$WORKSPACE_DIR/build"
	[ -d "$build_dir" ] || return 0
	local -a stale_dirs=()
	while IFS= read -r cache_file; do
		local cache_dir expected_dir generated_by
		cache_dir="$(dirname "$cache_file")"
		expected_dir="$(sed -n 's|^# For build in directory: ||p' "$cache_file" | head -n 1)"
		generated_by="$(sed -n 's|^# It was generated by CMake: ||p' "$cache_file" | head -n 1)"
		if [ -n "$expected_dir" ] && [ "$expected_dir" != "$cache_dir" ]; then
			stale_dirs+=("$cache_dir")
			continue
		fi

		if [[ "$generated_by" == *"/Users/"* ]] || [[ "$generated_by" == *"/macos/"* ]]; then
			stale_dirs+=("$cache_dir")
		fi
	done < <(find "$build_dir" -name "CMakeCache.txt" -type f 2>/dev/null || true)

	[ "${#stale_dirs[@]}" -gt 0 ] || return 0

	echo "[WARN] Detected stale CMake cache from a different environment."
	printf '%s\n' "${stale_dirs[@]}" | sort -u | while IFS= read -r stale_dir; do
		echo "[INFO] Removing stale build directory: ${stale_dir#$WORKSPACE_DIR/}"
		rm -rf "$stale_dir"
	done
}

# Clean cmake cache if switching between different host environments
# We have to do this because of the MacOS native workflow.
sanitize_cross_platform_artifacts

# Validate required resources
BRINGUP_PKG="${ROBOT_NAME}_bringup"
DESCRIPTION_PKG="${ROBOT_NAME}_description"

if [ ! -d "$BRINGUP_PKG" ]; then
	echo "[Error] Package '$BRINGUP_PKG' not found in $WORKSPACE_DIR"
	echo "        Expected directory: $WORKSPACE_DIR/$BRINGUP_PKG"
	exit 1
fi

if [ ! -d "$DESCRIPTION_PKG" ]; then
	echo "[Error] Package '$DESCRIPTION_PKG' not found in $WORKSPACE_DIR"
	echo "        Expected directory: $WORKSPACE_DIR/$DESCRIPTION_PKG"
	exit 1
fi

LAUNCH_FILE_NAME="${ROBOT_NAME}.launch.py"
LAUNCH_FILE_SRC="$BRINGUP_PKG/launch/$LAUNCH_FILE_NAME"
if [ ! -f "$LAUNCH_FILE_SRC" ]; then
	echo "[Error] Launch file not found: $LAUNCH_FILE_SRC"
	exit 1
fi

#

# Setup logging, print banner
mkdir -p "$LOG_DIR"
exec > >(tee >(sed -r 's/\x1B\[[0-9;]*[mK]//g' >>"$LOG_PATH")) 2>&1

echo "--------------------------------------------------------------"
echo "Robot:     $ROBOT_NAME"
echo "Simulator: gazebo"
echo "Workspace: $WORKSPACE_DIR"
echo "Log:       $LOG_PATH"
echo "--------------------------------------------------------------"

# Build ROS2 workspace
if [ "$BUILD" = true ]; then
	echo "[INFO] Building ROS2 workspace..."
	colcon build \
		--packages-up-to "$BRINGUP_PKG" "$DESCRIPTION_PKG" sim_worlds sim_common \
		--cmake-args -DBUILD_TESTING=OFF
	echo "[INFO] Build complete"
fi

# Source ROS2
echo "[INFO] Sourcing ROS2 environment..."
# shellcheck disable=SC1091
source install/setup.bash

# Add sim_worlds share directory to GZ_SIM_RESOURCE_PATH so Gazebo can find world files
SIM_WORLDS_SHARE="$WORKSPACE_DIR/install/sim_worlds/share/sim_worlds"
if [ -d "$SIM_WORLDS_SHARE/worlds" ]; then
	export GZ_SIM_RESOURCE_PATH="${GZ_SIM_RESOURCE_PATH:+$GZ_SIM_RESOURCE_PATH:}$SIM_WORLDS_SHARE"
	echo "[INFO] GZ_SIM_RESOURCE_PATH set to: $GZ_SIM_RESOURCE_PATH"
else
	echo "[Warn] sim_worlds share directory not found - world files may not load"
	echo "       Expected: $SIM_WORLDS_SHARE/worlds"
fi

# Launch simulation
if [ "$LAUNCH" = true ]; then
	echo ""
	echo "[INFO] Launching gazebo simulation for robot: $ROBOT_NAME"
	echo "------------------------------------------------------------"
	ros2 launch "$BRINGUP_PKG" "$LAUNCH_FILE_NAME" gui:=true
fi
