name: Style Check

on:
    push:
    pull_request:

jobs:
    Python:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7

            - name: Install Python
              uses: actions/setup-python@v7
              with:
                  python-version: "3.11"

            - name: Install Ruff
              run: |
                  python -m pip install --upgrade pip
                  pip install ruff==0.15.21

            - name: Run Ruff
              run: ruff check --output-format=github .
    Shell:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7

            - name: Install shfmt
              uses: mfinelli/setup-shfmt@v4

            - name: Check shell formatting
              run: shfmt -d .devcontainer/ docker/

    Cpp:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7

            - name: Check C++ formatting
              uses: jidicula/clang-format-action@v4.13.0
              with:
                  clang-format-version: "18"
                  check-path: "chrono"
