name: Style Check

on:
    push:
    pull_request:

jobs:
    python:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install Ruff
              run: |
                  python -m pip install --upgrade pip
                  pip install ruff==0.15.21

            - name: Run Ruff
              run: ruff check --output-format=github .

            - name: Install shfmt
              uses: mfinelli/setup-shfmt@v3

            - name: Check shell formatting
              run: shfmt -d .devcontainer/ docker/

    cpp:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Check C++ formatting
              uses: jidicula/clang-format-action@v4.13.0
              with:
                  clang-format-version: "18"
                  check-path: "chrono"
